language: node_js
sudo: required
dist: trusty
node_js:
- node
notifications:
  email: false
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
- npm install
- npm i -g gulp-cli
script:
- npm run build
- npm run test:coveralls
