language: node_js
sudo: required
dist: trusty
node_js:
- node
notifications:
  email: false
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
- npm install
script:
- npm run lint
- npm run build
- npm run coverage
env:
  secure: Z13nKKZm3UpfdEJRoCCrgd9YdoA1ldu+zRhdfAObFUVVy2ZwAPMImlsP8za28v+9r9TD873cQuiEwIgjhwG3a6aNkRlZXB7lldPx4oEG9HnYF5RdUI8tj7/L1shIObFbuherr/CvS4AHXGFM2JwkVaMOagILn9GfhTpGmunQCt9/5pywJCsfdUMOM90JdqwotfF96/dfAffEPlfEUO5unARN+rqZl+6UvCEbLXsYirV6O16G2xn5qg/IRo3UAYb5ZzglLnCtmv+0mzS100VDcsGcN51KFHQEVOU96mo9+ELpCQaxNa8QDm6m2LvAShR1sS0YfYFeaPkm+jZj01rGIVzY/3MopiWXZaohNRtcLdgB/oDwwusPSMBwxdlyzANQsdjm6nJDXqzO+1O/V5gzhd5bUePtWMzCaai+3qZ/edUY9Ple2FX0Xp7qY3MuTB9UWbXecFz0CdgxqHZff4XxzbvU+F6SwvUetJVfW/Qhjxw60AkNk633XBGgNKrn04s0KUqfiaLR1u5EMRMz/6u1+QI8w1APOeof0bC1K7zWc7Zh7EFB1Cvofkjx6sVoaBSzASyKMVDkpnIJl+lHEQ+PRcWixRDiDQmc8mH2Hr1aHAsAS65qVlxLjWSafjvu8upyupnelRhy1qleDjk8UB+x3nteyshjdVMHbaDC3NeUKF8=
