language: node_js
sudo: required
dist: trusty
node_js:
- node
notifications:
  email: false
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
- npm install
script:
- npm run lint
- npm run build
- npm test
