const simpleRequest = {
  Columns:
    [
      { Aggregate: 'None',
        DataType: 'numeric',
        Filter:
        { Argument: [],
          HasFilter: false,
          Name: 'OrderID',
          Operator: 'None',
          OptionsUrl: null,
          Text: null },
        IsKey: true,
        Label: 'Order ID',
        Name: 'OrderID',
        Searchable: false,
        SortDirection: 'Ascending',
        SortOrder: 1,
        Sortable: true,
        Visible: true },
      { Aggregate: 'Count',
        DataType: 'string',
        Filter:
        { Argument: [],
          HasFilter: false,
          Name: 'CustomerName',
          Operator: 'None',
          OptionsUrl: null,
          Text: null },
        IsKey: false,
        Label: 'Customer Name',
        Name: 'CustomerName',
        Searchable: true,
        Sortable: false,
        Visible: true },
      { Aggregate: 'None',
        DataType: 'datetime',
        Filter:
        { Argument: [],
          HasFilter: false,
          Name: 'ShippedDate',
          Operator: 'None',
          OptionsUrl: null,
          Text: null },
        IsKey: false,
        Label: 'Shipped Date',
        Name: 'ShippedDate',
        Searchable: false,
        Sortable: false,
        Visible: true },
      { Aggregate: 'None',
        DataType: 'string',
        IsKey: false,
        Label: 'Shipper City',
        Name: 'ShipperCity',
        Searchable: false,
        Sortable: false,
        Visible: true },
      { Aggregate: 'None',
        DataType: 'numeric',
        IsKey: false,
        Label: 'Amount',
        Name: 'Amount',
        Searchable: false,
        Sortable: false,
        Visible: true }
    ],
  Count: 0,
  Search: { Text: '', Operator: 'Auto' },
  Skip: 0,
  Take: 10,
  TimezoneOffset: 360 };

const page2Request = {
  Columns: [
    { Aggregate: 'None',
      DataType: 'numeric',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'OrderID',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: true,
      Label: 'Order ID',
      Name: 'OrderID',
      Searchable: false,
      SortDirection: 'Ascending',
      SortOrder: 1,
      Sortable: true,
      Visible: true },
    { Aggregate: 'Count',
      DataType: 'string',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'CustomerName',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Customer Name',
      Name: 'CustomerName',
      Searchable: true,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'datetime',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'ShippedDate',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Shipped Date',
      Name: 'ShippedDate',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'string',
      IsKey: false,
      Label: 'Shipper City',
      Name: 'ShipperCity',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'numeric',
      IsKey: false,
      Label: 'Amount',
      Name: 'Amount',
      Searchable: false,
      Sortable: false,
      Visible: true }
  ],
  Count: 1,
  Search: { Text: '', Operator: 'Auto' },
  Skip: 10,
  Take: 10,
  TimezoneOffset: 360 };

const descendingRequest = {
  Columns: [
    { Aggregate: 'None',
      DataType: 'numeric',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'OrderID',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: true,
      Label: 'Order ID',
      Name: 'OrderID',
      Searchable: false,
      SortDirection: 'Descending',
      SortOrder: 1,
      Sortable: true,
      Visible: true },
    { Aggregate: 'Count',
      DataType: 'string',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'CustomerName',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Customer Name',
      Name: 'CustomerName',
      Searchable: true,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'datetime',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'ShippedDate',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Shipped Date',
      Name: 'ShippedDate',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'string',
      IsKey: false,
      Label: 'Shipper City',
      Name: 'ShipperCity',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'numeric',
      IsKey: false,
      Label: 'Amount',
      Name: 'Amount',
      Searchable: false,
      Sortable: false,
      Visible: true }
    ],
  Count: 1,
  Search: { Text: '', Operator: 'Auto' },
  Skip: 0,
  Take: 10,
  TimezoneOffset: 360 };

const twentyRecordsRequest = {
  Columns: [
    { Aggregate: 'None',
      DataType: 'numeric',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'OrderID',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: true,
      Label: 'Order ID',
      Name: 'OrderID',
      Searchable: false,
      SortDirection: 'Ascending',
      SortOrder: 1,
      Sortable: true,
      Visible: true },
    { Aggregate: 'Count',
      DataType: 'string',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'CustomerName',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Customer Name',
      Name: 'CustomerName',
      Searchable: true,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'datetime',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'ShippedDate',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Shipped Date',
      Name: 'ShippedDate',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'string',
      IsKey: false,
      Label: 'Shipper City',
      Name: 'ShipperCity',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'numeric',
      IsKey: false,
      Label: 'Amount',
      Name: 'Amount',
      Searchable: false,
      Sortable: false,
      Visible: true } ],
  Count: 0,
  Search: { Text: '', Operator: 'Auto' },
  Skip: 0,
  Take: 20,
  TimezoneOffset: 360 };

const onlyMicrosoftRecordsRequest = {
  Columns: [
    { Aggregate: 'None',
      DataType: 'numeric',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'OrderID',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: true,
      Label: 'Order ID',
      Name: 'OrderID',
      Searchable: false,
      SortDirection: 'Ascending',
      SortOrder: 1,
      Sortable: true,
      Visible: true },
    { Aggregate: 'Count',
      DataType: 'string',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'CustomerName',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Customer Name',
      Name: 'CustomerName',
      Searchable: true,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'datetime',
      Filter:
      { Argument: [],
        HasFilter: false,
        Name: 'ShippedDate',
        Operator: 'None',
        OptionsUrl: null,
        Text: null },
      IsKey: false,
      Label: 'Shipped Date',
      Name: 'ShippedDate',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'string',
      IsKey: false,
      Label: 'Shipper City',
      Name: 'ShipperCity',
      Searchable: false,
      Sortable: false,
      Visible: true },
    { Aggregate: 'None',
      DataType: 'numeric',
      IsKey: false,
      Label: 'Amount',
      Name: 'Amount',
      Searchable: false,
      Sortable: false,
      Visible: true } ],
  Count: 0,
  Search: { Text: 'Microsoft', Operator: 'Auto' },
  Skip: 0,
  Take: 10,
  TimezoneOffset: 360 };

export { descendingRequest, onlyMicrosoftRecordsRequest, page2Request, simpleRequest, twentyRecordsRequest };
